# Generated by Django 3.1.2 on 2023-11-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_inscripciontaller_taller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='descripcion',
            field=models.CharField(max_length=900),
        ),
    ]
