# Generated by Django 3.1.2 on 2023-11-27 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20231127_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taller',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='taller',
            name='fecha_termino',
        ),
        migrations.RemoveField(
            model_name='taller',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='taller',
            name='sala',
        ),
        migrations.AddField(
            model_name='inscripciontaller',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripciontaller',
            name='fecha_termino',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripciontaller',
            name='instructor',
            field=models.CharField(default='fvera', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripciontaller',
            name='nota',
            field=models.FloatField(default='S01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripciontaller',
            name='sala',
            field=models.CharField(default='S011', max_length=50),
            preserve_default=False,
        ),
    ]
